name: CI

on: [push]

env:
  DEPLOY_PATH: /home/github-deploy-components/www
  # В теории можно собрать не только Vue-приложение, так как принцип сборки мало где отличается
  # BUILD_SCRIPT: npm run build
  BUILD_SCRIPT_OUTPUT: site

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      # Доставляем собранное приложение на сервер
      - name: Deploy to Server
        with:
          host: ${{ secrets.DEPLOY_ABRIS_HOST }}
          port: ${{ secrets.DEPLOY_ABRIS_PORT }}
          username: ${{ secrets.DEPLOY_ABRIS_USERNAME }}
          key: ${{ secrets.DEPLOY_ABRIS_KEY }}
          source: ${{ env.BUILD_SCRIPT_OUTPUT }}
          target: ${{ env.DEPLOY_PATH }}/
          # strip_components: 1
      - name: Print Info
        run: echo "Deployed at https://abris.site/new"
